package com.bartender.dao;

public class GlassesInsert {

	

	public static String[] sqlInsertGlasses = {"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(1,'rocks');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(2,'highball');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(3,'mug');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(4,'hurricane');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(5,'pint');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(6,'white wine');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(7,'wine');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(8,'cocktail');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(10,'champagne');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(12,'margarita');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(13,'shot');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(14,'sour');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(15,'pousse cafe');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(16,'parfait');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(17,'irish coffee');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(18,'pilsner');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(19,'punch');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(20,'snifter');"};
	

	public static String[] sqlInsertFractions= {"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(1,'⅛',0.125);"
		,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(2,'⅙',0.166);"
		,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(3,'⅕',0.2);"
		,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(4,'¼',0.25);"
		,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(5,'⅓',0.333);"
		,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(6,'⅜',0.375);"
		,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(7,'⅖',0.4);"
		,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(8,'½',0.5);"
		,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(9,'⅗',0.6);"
		,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(10,'⅝',0.625);"
		,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(11,'⅔',0.666);"
		,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(12,'¾',0.75);"
		,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(13,'⅘',0.8);"
		,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(14,'⅚',0.833);"
		,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(15,'⅞',0.875);"};

	
}
