package com.drinkmixer.dao;

public class GlassesInsert {

	

	public static String[] sqlInsertGlasses = {"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(1,'rocks');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(2,'highball');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(3,'mug');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(4,'hurricane');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(5,'pint');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(6,'white wine');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(7,'red wine');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(8,'cocktail');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(10,'champagne');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(12,'margarita');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(13,'shot');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(14,'sour');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(15,'pousse cafe');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(16,'parfait');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(17,'irish coffee');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(18,'pilsner');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(19,'punch');"
,"INSERT INTO "+DataDAO.TABLE_GLASSES+" VALUES(20,'snifter');"};
	

	public static String[] sqlInsertFractions= {"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(0,'---');"
												,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(1,'1/8');"
												,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(2,'1/6');"
												,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(3,'1/5');"
												,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(4,'1/4');"
												,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(5,'1/3');"
												,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(6,'3/8');"
												,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(7,'2/5');"
												,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(8,'1/2');"
												,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(9,'3/5');"
												,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(10,'5/8');"
												,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(11,'2/3');"
												,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(12,'3/4');"
												,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(13,'4/5');"
												,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(14,'5/6');"
												,"INSERT INTO "+DataDAO.TABLE_FRACTIONAL_AMOUNTS+" VALUES(15,'7/8');"};

	
}
